### ISSUE TITLE
[PE-D][Tester E] Poor formatting for Command Summary

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T08-4/tp#196]
![Screenshot 2023-11-03 at 4.29.28 PM.png](https://raw.githubusercontent.com/ryantzr1/ped/main/files/15eed13c-7982-4612-82ae-c6d61cf38263.png)

The command summary is very hard to read.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: ryantzr1/ped#6

**Comment by trgao** [comment]
Already fixed
