### ISSUE TITLE
[PE-D][Tester B] Command Summary Format in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T08-4/tp#216]
![Screenshot 2023-11-03 165349.png](https://raw.githubusercontent.com/Daphne789/ped/main/files/4b308f76-85e8-44e0-867f-7b2cf23780ff.png)

**The command summary table in the User Guide still has an issue since not showing the table as a whole**

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Daphne789/ped#1

**Comment by trgao** [comment]
Already fixed
