### ISSUE TITLE
[PE-D][Tester B] User Guide for Rescheduling an Appointment Feature

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T08-4/tp#227]
![image.png](https://raw.githubusercontent.com/Daphne789/ped/main/files/7006134d-4de6-4f74-bf1a-a13a116cc7e7.png)

**The highlighted blue text in the screenshot above is unclear since the _start_ and _end_ parameters value is needed to run the reschedule command.**

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Daphne789/ped#3

**Comment by trgao** [comment]
Same as #190
